// Mapa exhaustivo: nombre tal cual aparece en la hoja "Datos" del Excel
// (lowercase + trim) → código BD.
//
// Regla: un mismo código BD puede tener varios aliases (distintas etiquetas
// del Excel). Si el importer encuentra un nombre que NO está aquí, emite
// un warning explícito pero no rompe.

export const ALIAS_MATERIAL_EXCEL: Record<string, string> = {
  // ── Materias primas / minerales ───────────────────────────────────────
  "caliza + martillo":                                "CALIZATRI",
  "caliza triturada":                                 "CALIZATRI",
  "caliza en prehomo":                                "CALTLVTRIT",
  "caliza explotada":                                 "CALTLVTRIT",
  "caliza en crudo":                                  "CALTLVTRIT",
  "caliza en cemento ug":                             "CALTLVTRIT",
  "caliza en cemento art":                            "CALTLVTRIT",
  "caliza en cemento fibro":                          "CALTLVTRIT",
  "caliza comprada a externos":                       "CALIZAEXT",
  "costo adicional martillo":                         "COST_MART",
  "arcilla explotada":                                "ARCTLVTRIT",
  "arcilla en prehomo":                               "ARCTLVTRIT",
  "arcilla":                                          "ARCTLVTRIT",
  "puzolana":                                         "PUZOLANA",
  "puzolana en cemento ug":                           "PUZOLANA",
  "puzolana en cemento art":                          "PUZOLANA",
  "puzolana en cemento fibro":                        "PUZOLANA",
  "puzolana la dorada":                               "PUZ_DORADA",
  "mineral de hierro":                                "CORRHIERR",
  "calamina":                                         "CALAMINA",
  "calamina en crudo":                                "CALAMINA",
  "calamina gerdau - diaco":                          "CALAM_GERDA",
  "calamina sidoc":                                   "CALAM_SIDOC",
  "yeso":                                             "YESO00001",
  "yeso en cemento ug":                               "YESO00001",
  "yeso en cemento art":                              "YESO00001",
  "yeso en cemento fibro":                            "YESO00001",
  "yesos prada":                                      "YESO_PRADA",
  "yeso rey miranda":                                 "YESO_MIRAND",
  "etex":                                             "ETEX",
  "sal marina":                                       "SAL_MARINA",
  "sal marina en cemento ug":                         "SAL_MARINA",
  "sal marina en cemento art":                        "SAL_MARINA",
  "sal marina en cemento fibro":                      "SAL_MARINA",
  "ric":                                              "CORRHIERR",
  "ric en cemento ug":                                "CORRHIERR",
  "ric en cemento art":                               "CORRHIERR",
  "ric en cemento fibro":                             "CORRHIERR",
  "aditivo de molienda":                              "ADIT_MOL",
  "aditivo de molienda en cemento ug":                "ADIT_MOL",
  "aditivo de molienda en cemento art":               "ADIT_MOL",
  "aditivo de molienda en cemento fibro":             "ADIT_MOL",
  "aditivo cemento":                                  "ADITIVO_CEM",
  "finos filtro":                                     "FINOS_FILT",
  "finos filtro en cemento ug":                       "FINOS_FILT",
  "finos filtro en cemento art":                      "FINOS_FILT",
  "finos filtro en cemento fibro":                    "FINOS_FILT",
  "adpr - briceño":                                   "ADPR_BRICEN",
  "adpr - belencito":                                 "ADPR_BELENC",
  "tap (payandé)":                                    "TAP_PAYANDE",
  "exiros - atlantico":                               "EXIROS_ATL",
  "exiro - manizales":                                "EXIROS_MAN",
  "c i interamerican conmina (fortia minerals)":      "INTERAMER",

  // ── Semielaborados ────────────────────────────────────────────────────
  "prehomo":                                          "MEZCPREHO",
  "prehomo en crudo":                                 "MEZCPREHO",
  "harina cruda":                                     "HARINACRUD",
  "crudo en clinker":                                 "HARINACRUD",
  "carbón molido":                                    "CARBONMOL",
  "clinker":                                          "CLINKER001",
  "clinker en cemento ug":                            "CLINKER001",
  "clinker en cemento art":                           "CLINKER001",
  "clinker en cemento fibro":                         "CLINKER001",
  "combustibles":                                     "COMBALT",

  // ── Carbones (compras) ────────────────────────────────────────────────
  "carbón bituminoso":                                "CARBITUMI",
  "bituminoso":                                       "CARBITUMI",
  "bituminoso en carbón":                             "CARBITUMI",
  "carbón mixto":                                     "CARB_MIXTO",
  "carbones finos en carbón":                         "CARB_FINO",
  "carbón fino":                                      "CARB_FINO",
  "sanoha":                                           "CARB_SANOHA",
  "forero hernandez":                                 "CARB_FOREHE",
  "tottal carbón":                                    "CARB_TOTTAL",
  "soluciones de carbón colombia":                    "CARB_SOLUCI",
  "minas las margaritas":                             "CARB_LASMAR",
  "trancora sas":                                     "CARB_TRANCO",
  "mixto carbones andino":                            "CARB_ANDINO",
  "mixtos carbocoque":                                "CARB_COQUEC",
  "mixto coquecol":                                   "CARB_COQUEL",
  "impuesto al carbón":                               "IMP_CARBON",

  // ── Combustibles alternos ─────────────────────────────────────────────
  "cdr":                                              "CDR",
  "cdr en alternos":                                  "CDR",
  "tdf":                                              "TDF",
  "briquetas":                                        "BRIQUETAS",
  "briquetas en alternos":                            "BRIQUETAS",
  "briquetas arclad":                                 "BRIQ_ARCLAD",
  "chips":                                            "CHIPS",
  "chip de madera":                                   "CHIPS",
  "chip de madera en alternos":                       "CHIPS",
  "biochips biowatt":                                 "BIOCHIPS",
  "mezcla ponderado":                                 "MEZCLA_POND",
  "cdr focus green antioquia":                        "CDR_FG_ANT",
  "cdr sistema verde  cundinamarca":                  "CDR_SV_CUN",
  "cdr sistema verde cundinamarca":                   "CDR_SV_CUN",
  "cdr sistema verde antioquia":                      "CDR_SV_ANT",
  "cdr ecologística":                                 "CDR_ECOLOG",
  "cdr ecopositiva":                                  "CDR_ECOPOS",
  "cdr veolia":                                       "CDR_VEOLIA",
  "cdr gdi-cali":                                     "CDR_GDI_CAL",
  "cdr gdi-zipaquirá":                                "CDR_GDI_ZIP",
  "tdf sistema verde cundinamarca":                   "TDF_SV_CUN",
  "tdf sistema verde antioquia":                      "TDF_SV_ANT",
  "tdf focus green cundinamarca":                     "TDF_FG_CUN",
  "gasoil":                                           "GASOIL",
  "diesel":                                           "DIESEL",

  // ── Fletes ────────────────────────────────────────────────────────────
  "cdr flete (antioquia - planta)":                   "FLETE_CDR_ANT",
  "cdr flete (cundinamarca - planta)":                "FLETE_CDR_CUN",
  "cdr flete (cali - planta)":                        "FLETE_CDR_CALI",
  "flete (boyacá - planta)-socha":                    "FLETE_CARB_BOY_SOCHA",
  "flete (boyacá - planta)":                          "FLETE_CARB_BOY",
  "flete (antioquia - planta)":                       "FLETE_CARB_ANT",
  "flete (cundinamarca - planta)":                    "FLETE_CARB_CUN",
  "flete (caldas - planta)":                          "FLETE_CARB_CAL",
  "flete (cali - planta)":                            "FLETE_MP_CALI",
  "flete (barranquilla - planta)":                    "FLETE_MP_BARRANQ",
  "flete (cartagena - planta)":                       "FLETE_MP_CART",
  "flete (tolima - planta)":                          "FLETE_MP_TOLIMA",
  "flete (manizales - planta)":                       "FLETE_MP_MANIZALES",
  "flete (cartagena planta)":                         "FLETE_YESO_CART",
  "flete (maicao - planta)":                          "FLETE_YESO_MAICAO",
  "flete (mesa de los santos a planta)":              "FLETE_YESO_MS",
  "flete (la dorada a planta)":                       "FLETE_PUZ_LA_DORADA",

  // ── Repuestos y desgaste ──────────────────────────────────────────────
  "variables mtto":                                   "VARIABLES_MTTO",
  "var mtto":                                         "VARIABLES_MTTO",
  "empaque cemento":                                  "EMPAQUE_CEM",
  "barras trituradora":                               "BARRAS_TRITURADORA",
  "barras y placas":                                  "BARRAS_PLAC",
  "ductos del horno":                                 "DUCT_HORNO",
  "enfriador parrillas/trituradora":                  "ENFR_PARRIL",
  "enfriador horno":                                  "ENFR_HORNO",
  "placas horno":                                     "PLAC_HORNO",
  "elementos sellados horno":                         "SELLADO_HRN",
  "refractario horno":                                "REFR_HORNO",
  "masas molino crudo":                               "MASAS_CRUDO",
  "láminas crudo":                                    "LAM_CRUDO",
  "masas molino carbón":                              "MASAS_CARB",
  "anillos/tapas/separadores crudo":                  "ANI_TAP_SEP",
  "placas y segmentos rodillo cemento":               "PLAC_SEG_CEM",
  "cuerpos moledores":                                "CUERP_MOL",
  "placas y segmentos":                               "PLAC_SEG",
  "refractarios":                                     "REFRACTARIO",
  "material dique":                                   "MAT_DIQUE",

  // ── Servicios y operaciones ───────────────────────────────────────────
  "cargue clinker":                                   "CARGUE_CK",
  "cargue clinker venta":                             "CARG_CK_VENTA",
  "cargue clinker pm(en la tolva)":                   "CARG_CK_TOLVA",
  "cargue clinker a tolva":                           "CARG_CK_TOLVA",
  "cargue clinker (en tolva)":                        "CARG_CK_TOLVA",
  "cargue de alternos":                               "CARG_ALTERNOS",
  "descargue de alternos":                            "DESC_ALTERNOS",
  "descargue mp's":                                   "DESC_MP",
  "descargue mp":                                     "DESC_MP",
  "descarge finos (mini)":                            "DESC_FINOS_MINI",
  "descargue finos carbón":                           "DESC_FINOS_MINI",
  "cargador carbón":                                  "CARGADOR_CARBON",
  "desatasque de carbón":                             "DESATASQUE_CARB",
  "dosificacion sal":                                 "DOSIFIC_SAL",
  "dosificador de sal":                               "DOSIFIC_SAL",
  "empaque y cargue cemento":                         "CARGUE_CEM",
  "unitario empaque y granel":                        "EMP_UNITARIO",
  "empaque y granel":                                 "EMP_GRANEL",
  "fijo + horas extras empaque y granel":             "EMP_FIJO_HE",
  "regalías":                                         "REGALIAS",
  "precio regalías arcilla":                          "REGALIAS_ARCILLA",
  "precio regalías caliza":                           "REGALIAS_CALIZA",

  // ── Energía ───────────────────────────────────────────────────────────
  "energía eléctrica":                               "ENERGIA_KWH",
  "energia electrica":                               "ENERGIA_KWH",

  // ── Empaques ─────────────────────────────────────────────────────────
  "sacos 50 kg ug":                                   "SACO_50KG",
  "sacos para ug 50 kg":                              "SACO_50KG",
  "sacos 42,5 kg ug":                                 "SACO_42_5KG",
  "sacos para ug 42,5 kg":                            "SACO_42_5KG",
  "sacos 25 kg":                                      "SACO_25KG",
  "sacos para ug 25 kg":                              "SACO_25KG",
  "sacos 42,5 kg art":                                "SACO_42_ART",
  "sacos para art 42,5 kg":                           "SACO_42_ART",
  "sacos 50 kg topex":                                "SACO_50_TPX",
  "sacos para topex ug 50 kg":                        "SACO_50_TPX",
};

/** Normaliza un nombre del Excel para buscarlo en ALIAS_MATERIAL_EXCEL. */
export function normalizeMaterialName(s: string): string {
  return s
    .trim()
    .toLowerCase()
    .replace(/\s+/g, " ")
    .replace(/ /g, " ") // non-breaking space
    .replace(/\(pci\)\s*$/, "").trim(); // quita el sufijo " (PCI)" que aparece en combustibles
}
